# Generated by Django 5.1.4 on 2025-01-01 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_app', '0002_autocategory_cartechchar_category_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartechchar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='cartechchar',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auto_app.profile', verbose_name='Профиль'),
        ),
    ]
