# Generated by Django 5.1.4 on 2025-01-01 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_app', '0003_cartechchar_image_cartechchar_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarBrand',
            new_name='AutoBrand',
        ),
        migrations.RenameModel(
            old_name='CarModel',
            new_name='AutoModel',
        ),
        migrations.RenameModel(
            old_name='CarTechCHar',
            new_name='AutoTechCHar',
        ),
    ]
